### ISSUE TITLE
Fehler an der Property PaymentMethod beim Supplier

### ISSUE THREAD

**Issue by SemikolonDEV** [hamburger-software/ab-api#20]
Bei einem POST/PUT eines Lieferanten tritt ein Fehler auf, wenn für die Eigenschaft `PaymentMethod` der Wert `SepaTransferSingleInvoice` verwendet wird.

Fehlermeldung:

`{
    "HsErrorId": "0x1cba",
    "Message": "The input data is not correct (InvalidData).",
    "MessageDetail": "invalid data\r\nenum Zahltraeger __thiscall BusinessEnumConverterBase<enum Zahltraeger,class phoenix::Str>::convertToBusinessEnumValue(const class phoenix::Str &) const\r\nUnbekannte Ausprägung \"SepaTransferSingleInvoice\"\r\nclass CxeInvalidData\r\n"
}`

**Comment by aronkankel** [comment]
AIS 22594
