### ISSUE TITLE
BillOfMaterialProductItem -> Menge in PE/LE

### ISSUE THREAD

**Issue by Christian-Sachse** [hamburger-software/ab-api#24]
Ich wünschte mir noch Felder, in denen ich die Menge PE und LE und die jeweilige Einheit (readonly) abfragen kann. Ähnlich der Artikelposition

**Comment by aronkankel** [comment]
Idee:
Neue Properties an BillOfMaterialProductItem:
QuantityPerModuleInPriceUnits
QuantityPerModuleInDeliveryUnits
