### ISSUE TITLE
BillOfMaterialProductItem -> Gesamt Rest/Verleib/Abrufmenge -> PE/LE

### ISSUE THREAD

**Issue by Christian-Sachse** [hamburger-software/ab-api#26]
Wäre schön, wenn das für die bereits abgerufende, verbleibende Menge und noch abzurufende Menge auch die Werte in PE und LE gibt

**Comment by aronkankel** [comment]
Idee:
QuantityAlreadyProcessedInPriceUnits
QuantityAlreadyProcessedInDeliveryUnits
QuantityToProcessInPriceUnits
QuantityToProcessInDeliveryUnits

**Comment by aronkankel** [comment]
AIS 23030

- BillOfMaterialProductItem/QuantityInPriceUnits -> Neue Property für die effektive Menge in Preiseinheiten
- BillOfMaterialProductItem/QuantityInDeliveryUnits -> Neue Property für die effektive Menge in Liefereinheiten
- BillOfMaterialProductItem/QuantityAlreadyProcessedInPriceUnits -> Neue Property für die bereits abgerufene Menge in Preiseinheiten
- BillOfMaterialProductItem/QuantityAlreadyProcessedInDeliveryUnits -> Neue Property für die bereits abgerufene Menge in Liefereinheiten
- BillOfMaterialProductItem/QuantityToProcessInPriceUnits -> Neue Property für die noch abzurufende Menge in Preiseinheiten
- BillOfMaterialProductItem/QuantityToProcessInDeliveryUnits -> Neue Property für die noch abzurufende Menge in Liefereinheiten
