### ISSUE TITLE
Informationen zur Zeichnung (Fertigung) an Artikel und Fertigungsbeleg

### ISSUE THREAD

**Issue by aronkankel** [hamburger-software/ab-api#32]
Die Informationen zur Zeichnung (Registerkarte "Konstruktion") eines Fertigungsartikels sollten per API bereitgestellt werden.

Sie werden sowohl in den Stammdaten (Product) als auch im Fertigungsbeleg (ManufactureDocument, ManufactureLineItem) benötigt.

**Comment by aronkankel** [comment]
AIS 22865

Product / ManufactureDocument / ManufactureLineItem
- DrawingNumber
- DrawingCreationDate
- DrawingLastModified
- DrawingModificationStatus
- DrawingCreatedBy
- DrawingLastModifiedBy
- DrawingStatus

ManufactureDocument 
- ReferencedSalesDocumentCustomerId
- ReferencedSalesDocumentCustomerNumber

**Comment by Christian-Sachse** [comment]
Sehr schön, ich wollte das auch gerade hier reinschrieben - so hat sich das erledigt :)
