### ISSUE TITLE
Nettobetrag fehlt bei Lagerbuchungspositionen, die per API erzeugt wurden

### ISSUE THREAD

**Issue by aronkankel** [hamburger-software/ab-api#50]
Wenn man eine Lagerbuchung per API schreibt, dann ist bei deren Belegpositionen in der Datenbank die Spalte "vk_beleg_pos.einkaufswert" mit 0,00 besetzt. Das führt dazu, dass bei einer Belegabfrage mit Positionsdaten kein Wert in der Spalte "Netto Pos.Betrag" steht.

POST auf /v1/inventory-transactions
[Lagerbuchung.json](https://github.com/hamburger-software/ab-api/files/15387135/Lagerbuchung.json)

Über "Abfragen / Beleg" eine neue Belegabfrage mit folgenden Einstellungen erstellen:
Abfrageart: Positionsdaten
Belegauswahl: Lagerbuchungsbelege
Zusatzanzeigen: Belegpositionsdaten / Netto Pos.Betrag

Ergebnis:
Für den per API geschriebenen Beleg wird kein Wert für "Netto Pos.Betrag" angezeigt.
![grafik](https://github.com/hamburger-software/ab-api/assets/66121375/03700f11-518e-4885-99d9-f10c18f1c565)

**Comment by aronkankel** [comment]
AIS 23129

**Comment by Christian-Sachse** [comment]
Sehr schön, dass ist das Problem, welches wir auch in einem Kundenprojekt hatten.
