### ISSUE TITLE
Abruf einer Artikelposition als Stückliste mit SNR in den Bestandteilen

### ISSUE THREAD

**Issue by Christian-Sachse** [hamburger-software/ab-api#61]
Hallo zusammen,

für xtend.Lager habe ich einen Kunden, der einen nicht bestandsgeführten Stücklistenartikel mit bestandsgeführten Bestandteilen mit SNR hat. beim Abruf verlangt die Leitanwendung die Angabe von Seriennummern, was ja korrekt ist.

Ich ich das korrekt, dass dies aktuell per API noch nicht lösbar ist? SNR/CNR auf dem Hauptartikel geht, aber nicht in den Bestandteilen?!

Das Abruf-Model würde sich ziemlich aufblähen, da man so ja eine beliebig-tiefe Stückliste abbilden müsste. Vielleicht macht es daher Sinn, eine Art Mapping zwischen Quellzeile (kann ja auch eine Ebene in der STL sein) und den SNR/CNR zu machen. Dann kann man es für die Ebenen die es erfordern flach mit angeben? In dem Atemzug wäre es vielleicht sogar sinnvoll das gleiche auch mit dem BDFs zu machen. Ich müsste nämlich nicht nur SNR/CNR mitgeben, sondern hier auch BDFs setzen/ändern. Im "Hauptartikel" geht das ja auch.

Ich hoffe, man kann es verstehen, wie ich's geschrieben habe. Ansonsten bitte nochmal mal melden.

Dank + Gruß
Christian

**Comment by aronkankel** [comment]
Hallo @Christian-Sachse , derzeit ist keine Angabe von Serien-/Chargennummern für Bestandteile beim Abruf per API möglich.
Wann und wie ich es umsetze, kann ich derzeit noch nicht sagen.
Abhilfe bis dahin wäre, im abzurufenden Beleg per PUT die Serien-/Chargennummern einzutragen, bevor der Abruf erfolgt.

AIS 23204

**Comment by aronkankel** [comment]
Achtung! Beim PUT der Stückliste wird die vorhandene Stückliste komplett ersetzt und es ergeben sich neue IDs in der Datenbank.
Bei teilabgerufenen Belegen kann das zu Fehlern führen, siehe https://github.com/hamburger-software/ab-api/issues/14

Idee: Am TargetLineItem eine Liste von SNR/CNR inkl. BF mitgeben und die Id des Stücklistenbestandteils im Ursprungsbeleg für die Zuordnung.

AIS 23204, 21067, 21923

**Comment by Christian-Sachse** [comment]
Ich hatte eben den Workaround versucht zu implementieren und bin eben genau auf dieses Problem mit den geänderten Ids gestoßen. Das führt dazu, dass bei mir in dem nachgelagerten die Schlüssel verweisen und es zu abstürzen kommt. Ansonsten funktioniert dieser Workaround erst einmal. Nun werde ich versuchen die alten Ids in die neuen überzuleiten, dass ist schwer, da halt der Primärschlüssel fehlt. 

Vielleicht Abhilfe könnte noch sein, dass wir soetwas wie ein FremdanwendungID hier mitführen, so dass ich nicht suchen/raten, sondern gezielt über diese neu Zuordnen kann.
