### ISSUE TITLE
Belegposition: Stückliste mit Seriennummer und Produzieren

### ISSUE THREAD

**Issue by Christian-Sachse** [hamburger-software/ab-api#76]
Hallo zusammen,

ich habe ein Problem in der API entdeckt. 

Ich habe einen VK-Beleg mit einer Artikelposition mit Stückliste. 
* Der VK-Beleg ist reservierend (ist aber denke ich unerheblich)
* Der Stücklistenartikel ist selbst bestandsgeführt.
* Die Stückliste besteht aus einem Artikel, wiederum bestandsgeführt mit Seriennummer
* Die Stücklistenposition hat den "Produzieren-Haken"

In Bildern:
![image](https://github.com/user-attachments/assets/32516f00-5022-4708-9e01-138100ead73b)
![image](https://github.com/user-attachments/assets/79160646-66a3-4041-99c2-5fa7a6b85a09)
![image](https://github.com/user-attachments/assets/0c42ed49-b9f1-4912-8efc-41a88140d935)
![image](https://github.com/user-attachments/assets/f6091d9a-a0e1-433c-bbd9-5efcab10d5b0)

Der Abruf per API klappt wunderbar. Schickt man per PUT aber eine Aktualisierung, kommt der Fehler:
`{
    "HsErrorId": "6821",
    "Message": "The input data is not correct (InvalidData).",
    "MessageDetail": "Fehler für Artikel SA2 in Lager 1: Die Seriennummer kommt durch diese Position mehrfach auf diesem Lager vor. ( = <NULL> (PE))\r\n"
}`

Hier mein Beispiel JSON:

`{
    "Id": 19198,
    "LineItems": [
        {
            "LineItemType": "Product",
            "Id": 157067,
            "ProductLineItemData": {
                "IsForAssembly": true,
                "BillOfMaterial": {
                    "IngredientsForQuantity": 1.0,
                    "Items": [
                        {
                            "BillOfMaterialItemType": "Product",
                            "LineNumber": "1",
                            "BillOfMaterialProductItem": {
                                "QuantityPerModuleUnitIndicator": "PriceUnit",
                                "ProductNumber": "SA2",
                                "ProductId": 94,
                                "QuantityPerModule": 1.0,
                                "QuantityPerModuleUnit": "",
                                "QuantityPerModuleFactor1": null,
                                "QuantityPerModuleFactor2": null,
                                "QuantityPerModuleFactor3": null,
                                "QuantityPerModuleFactor4": null,
                                "UnitPrice": 0.0,
                                "IsForAssembly": false,
                                "AssemblyDate": "",
                                "BillOfMaterial": null,
                                "WorkingPlan": null,
                                "SerialOrLotNumbers": [
                                    {
                                        "SerialOrLotId": 2192,
                                        "SerialOrLotNumber": "SA1_001",
                                        "Quantity": 1,
                                        "DateOfManufacture": null,
                                        "DateOfExpiry": null,
                                        "UserDefinedFields": [
                                            {
                                                "Type": "Alphanumeric",
                                                "Number": 1,
                                                "Name": "Hersteller",
                                                "AlphanumericValue": null,
                                                "NumericValue": null,
                                                "DateValue": null
                                            }
                                        ]
                                    }
                                ]
                            },
                            "BillOfMaterialTextBlockItem": null,
                            "DoPrint": true,
                            "Notes": ""
                        }
                    ]
                }
            }
        }
    ]
}`

Es ist nicht möglich den Beleg per API zu speichern oder zu ändern. Mein Anwendungsfall ist, hier bei der Stückliste Seriennummern einzutragen (Workaround zu #61). 

Das Verhalten ist reproduzierbar und hängt offenbar mit dem "Produzieren-Haken" zusammen. Änderungen an den Stücklisten ohne diesen Haken funktionieren problemlos.

Bitte prüfen und abstellen :) Bei Fragen gern melden.
LG Christian

**Comment by aronkankel** [comment]
AIS 23248
