### ISSUE TITLE
Belegabruf: Lieferdatum

### ISSUE THREAD

**Issue by Christian-Sachse** [hamburger-software/ab-api#82]
Hallo zusammen,

beim Belegabruf ist es ja möglich, eine neues Lieferdatum mitzugeben. Funktioniert auch prima. Wenn alle Positionen des Belegs das gleiche (ehemalige) oder kein Lieferdatum haben wird es auch in die Positionen übernommen. Gibt es Positionen mit abweichenden Lieferdatum wird es nicht übernommen. Dann muss ich den Zielebeleg laden und dort das Lieferdatum positionsweise korrigieren. Das ist etwas mühsam, da wir ja angehalten sind per "PUT-PATCH" nur die Änderungen mitzugeben (sprich ich muss das Model minimizen).

Es wäre viel Einfacher, wenn wir im Abrufmodel ein Flag hätten um das Lieferdatum für alle Positionen zu erzwingen. :)

LG Christian

**Comment by aronkankel** [comment]
Hallo @Christian-Sachse , hast du schon mal probiert, am TargetLineItem das DeliveryDate zu besetzen? Oder ist dir das zu aufwändig und du möchtest einfach alle Positionen abrufen, ohne dabei die LineItems am TargetDocumentData zu füllen?

**Comment by aronkankel** [comment]
AIS 23368

**Comment by Christian-Sachse** [comment]
Hallo Aron, das DeliveryDate am TargetLineItem  hatte ich gar nicht auf dem Schirm. Im einem Anwendungsfall war ein Komplett-Abruf eines Belegs. Überlegt ist es hier auch leichter den Zielbeleg zu ändern, als das Abrufmodell anzupassen. Danke aber für den Tipp mit dem TargetlineItem. Macht schon Sinn, die yaml bzl. das IntelliSense komplett zu lesen :)

**Comment by aronkankel** [comment]
Abhilfe ist dann, das Lieferdatum an der Ziel-Position mitzugeben (TargetLineItem/DeliveryDate).

Damit schließe ich den Issue.
