### ISSUE TITLE
AveragePrice immer null

### ISSUE THREAD

**Issue by l-eling** [hamburger-software/ab-api#84]
Hallo,

wenn ich über die Endpunkte `/v1/products` oder `/v1/products/{productId}` den Durchschnittspreis eines Artikels auslesen will bekomme ich immer nur `null` zurück. Also in der Property AveragePrice scheint generell immer nur `null` zu stehen.
In der Datenbank in vk_artikel.preis_dek und über die Oberfläche der AB sehe ich das ein Durchschnittspreis vorhanden ist.

HS Version ist 3.70 01/02

**Comment by aronkankel** [comment]
Hallo @l-eling , da hast du einen Bug gefunden. Ich behebe ihn zur nächsten Version (AB 3.70 02/00), die voraussichtlich zum Jahresende kommen wird.

**Comment by aronkankel** [comment]
AIS 23416
